### ISSUE TITLE
Assets: "AssetsHolding.Amount" reports wrong value if value has decimals (4.0.0-pre.20)

### ISSUE THREAD

**Issue by FerGT50** [CareBoo/unity-algorand-sdk#197]
I created an ASA with: total supply = 100 , 1 decimal
https://testnet.algoexplorer.io/tx/WIUNX7FFDUZE7SAXC6ZDAAP5SDZIA6UMFZLUH5U7BV2NXIMHN75A

AssetsHolding.Amount reports "1000"

Moreover, as written in Discussions, the other ASA properties "Unit", "Name" and "URL" are missing in AssetsHolding structure (https://careboo.github.io/unity-algorand-sdk/4.0/api/Algorand.Unity.Indexer.AssetHolding.html), maybe there is some other way to retrieve those properties?

Many thanks

**Comment by jasonboukheir** [comment]
Hi, thanks for using this SDK!

The `AssetsHolding.Amount` equals "asset units", or the total number of divisible units of the asset. To get the decimal version, divide it by `10**Decimals` (in your case, divide it by `10**1` or just `10`). This is the expected return value from the Algorand indexer node.

The `AssetHolding` details can be gotten from [`LookupAssetByID`](https://careboo.github.io/unity-algorand-sdk/4.0/api/Algorand.Unity.IndexerClient.html#Algorand_Unity_IndexerClient_LookupAssetByID_System_UInt64_Algorand_Unity_Optional_System_Boolean__).

**Comment by jasonboukheir** [comment]
I did some more digging. Let's define some terms for this conversation because it will be confusing.

| Name               | Definition                                              |
|--------------------|---------------------------------------------------------|
| integer units      | smallest possible unit of an asset                      |
| fractional units   | 10^decimals of an atomic unit (or just 1.0) of an asset |

With this in mind, `AssetParams.Total` is either in integer units or fractional units, and `AssetHolding.Amount` is either in integer units or fractional units.

Users are allowed to own fractional amounts of base units. Since `AssetHolding.Amount` is an integer, it must be in integer units. This leaves us to the matter of if `AssetParams.Total` is in integer or fractional units.

Let's use your example of
- Total = 100
- Decimals = 1

If `AssetParams.Total` is in integer units, then the fractional unit representation should be `10.0`. If it's in fractional units, then the total should be `100.0`. Testing it against [AlgoExplorer](https://testnet.algoexplorer.io/address/5D25TEVFHENIUCXA3JUMNAC72QNWGHN7N3PX36TH6YFZKZ2MTLS2NZQ3J4) shows a balance of `100`. Here we're still unsure if the AlgoExplorer representation is in fractional vs integer units, but we can figure it out. Transfer `0.1` of your asset to another account, leaving your balance at `9.9`. If AlgoExplorer is showing it in integer units, it will display your balance as `99`. If it's using fractional units, it will display it as `99.9`.

Or in other words, if AlgoExplorer shows your balance as `99.9`, then the Total of 100 should be treated as `100.0`. If it shows `99`, then the Total of 100 should be treated as `10.0`, and you've identified a bug somewhere in the indexer client.

**Comment by jasonboukheir** [comment]
Look at the assets in this account:
https://testnet.algoexplorer.io/address/J2ZRXFY7MYTNJWCWEC6BPZVDXT62Z3KL3AARLLASEZNOJULXSKSZY6S6G4
![Screenshot 2023-02-22 155427](https://user-images.githubusercontent.com/5115126/220790687-cb4bbb7e-a8f9-4b00-adfd-b52563e2eda7.png)

The Balance shown in AlgoExplorer is in fractional units, so the 1000 you're getting back from `AssetHolding.Amount` is not a bug. Whew! The documentation in Algorand developer portal sure is confusing, but really, when you create a new ASA, the total integer units of the resulting asset is `Total * 10^Decimals`.
